name: ml-from-scratch

dependencies:
  - python=3.6
  - pip
  - pip:
      - --trusted-host=pypi.python.org
      - --trusted-host=pypi.org
      - --trusted-host=files.pythonhosted.org
      - -r requirements.txt
